import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, LogOut, Mail, Phone, Search, ShieldCheck, Trash2, UserRound, Building2, ExternalLink } from 'lucide-react';

type Status = 'new' | 'reviewing' | 'contacted' | 'meeting' | 'proposal' | 'won' | 'lost';
interface Lead { id:string; businessName:string; contactName:string; email:string; phone:string; website:string; partnershipType:string; monthlyOrders:string; launchWindow:string; goals:string; status:Status; adminNotes:string; createdAt:string; updatedAt:string; }

const statuses: {value:Status; label:string}[] = [
  {value:'new',label:'New'},{value:'reviewing',label:'Reviewing'},{value:'contacted',label:'Contacted'},{value:'meeting',label:'Meeting Scheduled'},{value:'proposal',label:'Proposal Sent'},{value:'won',label:'Won'},{value:'lost',label:'Lost'}
];

export default function AdminApp(){
  const [token,setToken] = useState(() => sessionStorage.getItem('ordersphere_admin_token') || '');
  const [password,setPassword] = useState('');
  const [leads,setLeads] = useState<Lead[]>([]);
  const [selected,setSelected] = useState<Lead|null>(null);
  const [query,setQuery] = useState('');
  const [status,setStatus] = useState<'all'|Status>('all');
  const [loading,setLoading] = useState(false);
  const [error,setError] = useState('');

  const api = async (method:string, body?:unknown) => {
    const response = await fetch('/api/partner-leads', { method, headers: {'Content-Type':'application/json', ...(token ? {Authorization:`Bearer ${token}`} : {})}, body: body ? JSON.stringify(body) : undefined });
    const data = await response.json().catch(() => ({}));
    if (response.status === 401) { logout(); throw new Error('Your admin session has expired.'); }
    if (!response.ok) throw new Error(data.error || 'Request failed.');
    return data;
  };

  const load = async () => { if(!token) return; setLoading(true); setError(''); try { const data = await api('GET'); setLeads(data.leads || []); } catch(e){ setError(e instanceof Error ? e.message : 'Unable to load applications.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [token]);

  const login = async (e:React.FormEvent) => { e.preventDefault(); setError(''); setLoading(true); try { const response=await fetch('/api/admin-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.error || 'Invalid password.'); sessionStorage.setItem('ordersphere_admin_token',data.token); setToken(data.token); setPassword(''); } catch(e){ setError(e instanceof Error ? e.message : 'Login failed.'); } finally { setLoading(false); } };
  const logout = () => { sessionStorage.removeItem('ordersphere_admin_token'); setToken(''); setLeads([]); setSelected(null); };
  const updateLead = async (patch:Partial<Lead>) => { if(!selected) return; try { const data=await api('PATCH',{id:selected.id,...patch}); setSelected(data.lead); setLeads(prev=>prev.map(l=>l.id===data.lead.id?data.lead:l)); } catch(e){ setError(e instanceof Error ? e.message : 'Update failed.'); } };
  const removeLead = async () => { if(!selected || !confirm('Delete this partner application permanently?')) return; try { await api('DELETE',{id:selected.id}); setLeads(prev=>prev.filter(l=>l.id!==selected.id)); setSelected(null); } catch(e){ setError(e instanceof Error ? e.message : 'Delete failed.'); } };

  const filtered = useMemo(()=>leads.filter(l=> (status==='all'||l.status===status) && [l.businessName,l.contactName,l.email,l.phone].join(' ').toLowerCase().includes(query.toLowerCase())),[leads,status,query]);
  const counts = statuses.reduce((a,s)=>({...a,[s.value]:leads.filter(l=>l.status===s.value).length}),{} as Record<Status,number>);

  if(!token) return <div className="min-h-screen bg-[#020408] text-slate-200 flex items-center justify-center p-6"><form onSubmit={login} className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[0.03] p-8 shadow-2xl"><div className="w-12 h-12 rounded-xl bg-blue-600 flex items-center justify-center mb-5"><ShieldCheck className="w-6 h-6 text-white"/></div><h1 className="text-2xl font-bold text-white">Ordersphere Admin</h1><p className="text-sm text-slate-400 mt-2 mb-6">Secure partner application management.</p><label className="text-xs font-semibold text-slate-300">Admin Password</label><input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full bg-[#020408] border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-blue-500" required />{error&&<div className="mt-3 text-xs text-red-300">{error}</div>}<button disabled={loading} className="mt-5 w-full rounded-full bg-blue-600 hover:bg-blue-500 disabled:opacity-50 py-3 font-semibold text-white">{loading?'Signing in...':'Sign In'}</button></form></div>;

  return <div className="min-h-screen bg-[#020408] text-slate-200 font-sans"><header className="sticky top-0 z-30 border-b border-white/10 bg-[#020408]/90 backdrop-blur-xl"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between"><div><div className="text-xl font-bold text-white">ORDERSPHERE <span className="text-blue-400">ADMIN</span></div><div className="text-xs text-slate-500">Partner Applications & Lead Management</div></div><div className="flex gap-2"><button onClick={load} className="px-4 py-2 rounded-full bg-white/[0.04] border border-white/10 text-xs">Refresh</button><button onClick={logout} className="px-4 py-2 rounded-full bg-white/[0.04] border border-white/10 text-xs flex items-center gap-2"><LogOut className="w-3.5 h-3.5"/>Logout</button></div></div></header>
    <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8"><div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-3 mb-6">{statuses.map(s=><button key={s.value} onClick={()=>setStatus(s.value)} className={`rounded-2xl border p-4 text-left ${status===s.value?'border-blue-500 bg-blue-500/10':'border-white/10 bg-white/[0.02]'}`}><div className="text-2xl font-bold text-white">{counts[s.value]}</div><div className="text-[11px] text-slate-400">{s.label}</div></button>)}</div>
      {error&&<div className="mb-4 rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</div>}
      <div className="flex flex-col sm:flex-row gap-3 mb-5"><div className="relative flex-1"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search business, contact, email or phone..." className="w-full bg-white/[0.03] border border-white/10 rounded-xl py-2.5 pl-10 pr-4 text-sm text-white focus:outline-none focus:border-blue-500"/></div><select value={status} onChange={e=>setStatus(e.target.value as 'all'|Status)} className="bg-[#050811] border border-white/10 rounded-xl px-4 py-2.5 text-sm"><option value="all">All Applications</option>{statuses.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></div>
      <div className="grid lg:grid-cols-[1fr_420px] gap-5"><section className="rounded-2xl border border-white/10 overflow-hidden"><div className="px-5 py-4 border-b border-white/10 text-sm font-semibold text-white">Applications ({filtered.length})</div>{loading?<div className="p-8 text-sm text-slate-400">Loading applications...</div>:filtered.length===0?<div className="p-10 text-center text-sm text-slate-500">No applications found.</div>:<div className="divide-y divide-white/5">{filtered.map(l=><button key={l.id} onClick={()=>setSelected(l)} className={`w-full text-left p-5 hover:bg-white/[0.03] ${selected?.id===l.id?'bg-blue-500/[0.06]':''}`}><div className="flex items-start justify-between gap-3"><div><div className="font-semibold text-white">{l.businessName}</div><div className="text-xs text-slate-400 mt-1">{l.contactName} · {l.email}</div></div><StatusBadge status={l.status}/></div><div className="text-[11px] text-slate-500 mt-3">{l.partnershipType} · {l.monthlyOrders} · {new Date(l.createdAt).toLocaleString()}</div></button>)}</div>}</section>
      <aside className="rounded-2xl border border-white/10 bg-white/[0.02] p-5 h-fit lg:sticky lg:top-24">{selected?<><div className="flex items-start justify-between"><div><div className="text-lg font-bold text-white">{selected.businessName}</div><div className="text-xs text-slate-400 mt-1">{selected.contactName}</div></div><button onClick={()=>setSelected(null)} className="text-slate-500">×</button></div><div className="mt-5 space-y-3 text-sm"><Info icon={<Mail/>} value={selected.email}/><Info icon={<Phone/>} value={selected.phone||'—'}/><Info icon={<Building2/>} value={selected.partnershipType}/><Info icon={<Clock3/>} value={selected.monthlyOrders}/><Info icon={<CalendarIcon/>} value={selected.launchWindow}/>{selected.website&&<Info icon={<ExternalLink/>} value={selected.website}/>}</div><div className="mt-5"><label className="text-xs font-semibold text-slate-300">Status</label><select value={selected.status} onChange={e=>updateLead({status:e.target.value as Status})} className="mt-2 w-full bg-[#050811] border border-white/10 rounded-xl px-3 py-2.5 text-sm">{statuses.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></div><div className="mt-4"><label className="text-xs font-semibold text-slate-300">Admin Notes</label><textarea value={selected.adminNotes} onChange={e=>setSelected({...selected,adminNotes:e.target.value})} onBlur={()=>updateLead({adminNotes:selected.adminNotes})} rows={4} placeholder="Internal notes..." className="mt-2 w-full bg-[#050811] border border-white/10 rounded-xl px-3 py-2.5 text-sm text-white focus:outline-none focus:border-blue-500"/></div><div className="mt-4 rounded-xl border border-white/10 bg-black/20 p-4"><div className="text-xs font-semibold text-slate-300 mb-2">Customer Request</div><p className="text-sm text-slate-400 whitespace-pre-wrap">{selected.goals || 'No workflow requirements provided.'}</p></div><div className="mt-5 flex gap-2"><a href={`mailto:${selected.email}`} className="flex-1 rounded-xl bg-blue-600 py-2.5 text-center text-xs font-semibold text-white">Email Customer</a><button onClick={removeLead} className="rounded-xl border border-red-500/30 text-red-300 px-3"><Trash2 className="w-4 h-4"/></button></div></>:<div className="py-12 text-center text-slate-500 text-sm">Select an application to view details.</div>}</aside></div>
    </main></div>;
}

const StatusBadge=({status}:{status:Status})=><span className="text-[10px] uppercase tracking-wide rounded-full px-2.5 py-1 bg-blue-500/10 text-blue-300 border border-blue-500/20">{statuses.find(s=>s.value===status)?.label}</span>;
const Info=({icon,value}:{icon:React.ReactNode;value:string})=><div className="flex items-center gap-2 text-slate-300"><span className="text-blue-400 [&>svg]:w-4 [&>svg]:h-4">{icon}</span><span className="break-all">{value}</span></div>;
const CalendarIcon=()=> <Clock3/>;
